{
 "title": "云边协同 - 全局监控大屏",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "device",
    "label": "设备选择",
    "query": "云端 : dcgm-exporter:9400|node-exporter:9100, 边端 : 10.144.144.3:9100|10.144.144.3:9400"
   }
  ]
 },
 "panels": [
  {
   "title": "已用显存",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FB_USED{instance=~\"$device:.*\"} * 1048576",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU 使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=~\"$device:.*\"}[1m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=~\"$device:.*\"} - node_memory_MemAvailable_bytes{instance=~\"$device:.*\"}) / node_memory_MemTotal_bytes{instance=~\"$device:.*\"} * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "网络吞吐量 (上传/下载)",
   "type": "timeseries",
   "description": "queryA（绿色线条）查询下载速率；\nqueryB（黄色线条）查询上传速率",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (device) (rate(node_network_receive_bytes_total{instance=~\"${device}:9100\",device!~\"lo|docker.*|veth.*|br-.*|cni.*\"}[1m]))",
     "legendFormat": "{{device}} 下载/接收"
    },
    {
     "expr": "sum by (device) (rate(node_network_transmit_bytes_total{instance=~\"${device}:9100\",device!~\"lo|docker.*|veth.*|br-.*|cni.*\"}[1m]))",
     "legendFormat": "{{device}} 上传/发送"
    }
   ]
  },
  {
   "title": "GPU 核心温度",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{instance=~\"$device:.*\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}