{
 "title": "昇腾-云端监控大屏",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "昇腾CPU使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=~\"^10.144.144.4:9100$\"}[1m])) * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "昇腾内存使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "label_replace(\r\n  (node_memory_MemTotal_bytes{instance=~\"10.144.144.4:.*\"} - node_memory_MemAvailable_bytes{instance=~\"10.144.144.4:.*\"}) / node_memory_MemTotal_bytes{instance=~\"10.144.144.4:.*\"} * 100,\r\n  \"device_name\", \"☁️ 云端节点 (Ascend 910B4 x2)\", \"instance\", \".*\"\r\n)\r\n\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "昇腾网络吞吐量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "label_replace(rate(node_network_receive_bytes_total{device=~\"eth0|enp.*\", instance=~\"10.144.144.4:.*\"}[1m]), \"device_name\", \"☁️ 云端节点 (Ascend 910B4 x2)\", \"device\", \".*\")",
     "legendFormat": "{{device}} 接收"
    }
   ]
  },
  {
   "title": "昇腾NPU显存用量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "ascend_npu_hbm_usage_ratio{job=\"npu-metrics\", instance=\"10.144.144.4:9500\"} * 100",
     "legendFormat": "NPU {{npu_id}} 显存"
    }
   ]
  },
  {
   "title": "昇腾NPU温度",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ascend_npu_temperature_celsius{job=\"npu-metrics\", instance=\"10.144.144.4:9500\"}",
     "legendFormat": "NPU {{npu_id}}"
    }
   ]
  }
 ]
}