global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
          - "127.0.0.1:9091"

  - job_name: "node-metrics"
    static_configs:
      - targets:
          - "10.144.144.4:9100"
        labels:
          device_id: "cloud"
          device_name: "cloud-node"
          device_type: "cloud"
          exporter_type: "node_exporter"