global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
          - "127.0.0.1:9091"

  - job_name: "node-metrics"
    http_sd_configs:
      - url: "http://127.0.0.1:8010/api/v1/system/devices/prometheus/targets/node"
        refresh_interval: 30s

  - job_name: "gpu-metrics"
    http_sd_configs:
      - url: "http://127.0.0.1:8010/api/v1/system/devices/prometheus/targets/gpu"
        refresh_interval: 30s

  - job_name: "npu-metrics"
    http_sd_configs:
      - url: "http://127.0.0.1:8010/api/v1/system/devices/prometheus/targets/npu"
        refresh_interval: 30s
